// <auto-generated />
namespace DoAnWebBanGiay.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddProSize : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddProSize));
        
        string IMigrationMetadata.Id
        {
            get { return "202411240814166_AddProSize"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
